spring:
  datasource:
    url: ${definition.db.url-jdbc}/test_dbdave?${definition.db.option-jdbc}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: dave
    password: "0000"
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

jwt:
  secret: ImPossible$$
  token-validity-ms: 86400000

directory:
  user:
    image: /home/JENKINS/template/test_develop/data/user/image

logging:
  config: classpath:logback-spring-test-develop.xml
