definition:
#  host: 192.168.123.87
  host: 192.168.200.172
#  host: 192.168.45.174
  db:
    url: jdbc:log4jdbc:mariadb://${definition.host}:19000
    option: characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true

server:
  port: 18020
  servlet:
    contextPath: /template

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

jwt:
  name-token-access: tokenAccess
  name-terms-remaining-token-access: termsRemainingTokenAccess
  name-token-refresh: tokenRefresh
  name-terms-remaining-token-refresh: termsRemainingTokenRefresh

mybatis:
  mapper-locations: classpath:/mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

logging:
  config: classpath:logback-spring.xml

---

spring:
  config:
    activate:
      on-profile: "develop"
    import:
      - classpath:/env/develop/application.yml

---

spring:
  config:
    activate:
      on-profile: "local"
    import:
      - classpath:/env/local/application.yml

---

spring:
  config:
    activate:
      on-profile: "service"
    import:
      - classpath:/env/service/application.yml

---

spring:
  config:
    activate:
      on-profile: "test"
    import:
      - classpath:/env/test/application.yml
