definition:
#  host: 192.168.200.109
  host: 192.168.45.159
  db:
    url-jdbc: jdbc:log4jdbc:mariadb://${definition.host}:19000
    option-jdbc: characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true

server:
  port: 18020
  servlet:
    contextPath: /template

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  data:
    redis:
      host: ${definition.host}
      port: 19030
      password: "0000"

mybatis:
  mapper-locations: classpath:/mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# logging:
#   level:
#     org:
#       springframework: INFO
#     com:
#       example:
#         template: TRACE
#     log4jdbc:
#       log4j2: ERROR
#    jdbc:
#      sqlonly: TRACE
#      sqltiming: TRACE
#      resultsettable: TRACE
#      audit: TRACE
#      resultset: TRACE
#      connection: TRACE

---

spring:
  config:
    activate:
      on-profile: "develop"
    import:
      - classpath:/env/develop/application.yml

---

spring:
  config:
    activate:
      on-profile: "local"
    import:
      - classpath:/env/local/application.yml

---

spring:
  config:
    activate:
      on-profile: "service"
    import:
      - classpath:/env/service/application.yml

---

spring:
  config:
    activate:
      on-profile: "test_develop"
    import:
      - classpath:/env/test_develop/application.yml

---

spring:
  config:
    activate:
      on-profile: "test_local"
    import:
      - classpath:/env/test_local/application.yml

---

spring:
  config:
    activate:
      on-profile: "test_server"
    import:
      - classpath:/env/test_server/application.yml
