@BaseURL0 = http://localhost:18020/template/api/v0
@BaseURL1 = http://localhost:18020/template/api/v1


### SignUp
POST {{BaseURL1}}/auth/signup HTTP/1.1
content-Type: application/json

{
    "username": "newuser",
    "password": "0000",
    "roles": ["ROLE_ADMIN", "ROLE_MANAGER"]
}

### SignIn
# @name signIn
POST {{BaseURL1}}/auth/signin HTTP/1.1
content-Type: application/json

{
    "username": "uuser",
    "password": "0000"
}

@tokenAccess = {{signIn.response.body.tokenAccess}}
@tokenRefresh = {{signIn.response.body.tokenRefresh}}



### sampleAha GetOne
GET {{BaseURL0}}/sample-aha/one?id=1 HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}


### sampleAha GetList
GET {{BaseURL0}}/sample-aha/list?pageNumber=2&pageSize=2 HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}


### sampleAha GetSearch
GET {{BaseURL0}}/sample-aha/search?foo=한글&bar=10&pageNumber=1&pageSize=2 HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}


### sampleAha PostOne
POST {{BaseURL0}}/sample-aha/one HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

{
    "foo": "아니다 수요일이다",
    "bar": 1234
}


### sampleAha PostList
POST {{BaseURL0}}/sample-aha/list HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

[
    {
        "foo": "주중이다",
        "bar": 3333
    },
    {
        "foo": "즐겁고",
        "bar": 3333
    },
    {
        "foo": "보람차게",
        "bar": 3333
    }
]


### sampleAha PutOne
PUT {{BaseURL0}}/sample-aha/one HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

{
    "id": 155,
    "foo": "PUT으로 새로운 한 주 시작",
    "bar": 12345
}


### sampleAha PutList
PUT {{BaseURL0}}/sample-aha/list HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

[
    {
        "id": 156
    },
    {
        "id": 157,
        "foo": "PUT리스트 새로운 한 주 시작",
        "bar": 1234
    }
]


### sampleAha DeleteOne
DELETE {{BaseURL0}}/sample-aha/one HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

{
    "id": 155
}


### sampleAha DeleteList
DELETE {{BaseURL0}}/sample-aha/list HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

[
    {
        "id": 152
    },
    {
        "id": 153
    }
]




### sampleSimple GetOne
GET {{BaseURL0}}/sample-simple/one?id=14 HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}


### sampleSimple GetAll
GET {{BaseURL0}}/sample-simple/all?pageNumber=8&pageSize=7 HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}


### sampleSimple GetSearch
GET {{BaseURL0}}/sample-simple/search?bar=18&pageNumber=2&pageSize=4 HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}


### sampleSimple PostOne
POST {{BaseURL0}}/sample-simple/one HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

{
    "foo": "새로운 한 주",
    "bar": 1234
}


### sampleSimple PostList
POST {{BaseURL0}}/sample-simple/list HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

[
    {
        "foo": "새로운 한 주 시작",
        "bar": 1234
    },
    {
        "foo": "새로운 한 주 즐겁고",
        "bar": 1234
    },
    {
        "foo": "새로운 한 주 보람차게",
        "bar": 1234
    }
]


### sampleSimple PutOne
PUT {{BaseURL0}}/sample-simple/one HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

{
    "id": 155,
    "foo": "PUT으로 새로운 한 주 시작",
    "bar": 12345
}


### sampleSimple PutList
PUT {{BaseURL0}}/sample-simple/list HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

[
    {
        "id": 156
    },
    {
        "id": 157,
        "foo": "PUT리스트 새로운 한 주 시작",
        "bar": 1234
    }
]


### sampleSimple DeleteOne
DELETE {{BaseURL0}}/sample-simple/one HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

{
    "id": -151,
    "status": 777
}


### sampleSimple DeleteList
DELETE {{BaseURL0}}/sample-simple/list HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

[
    {
        "id": 152,
        "status": 777
    },
    {
        "id": 153,
        "status": 777
    }
]






### sampleQuery Select
POST {{BaseURL0}}/sample-query/execute-query HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

{
    "query": "SELECT * FROM aha_user WHERE username = 'uuser'"
}




### sampleAnnotation GetOne
GET {{BaseURL0}}/sample-annotation/one?id=0 HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}


### sampleAnnotation GetAll
GET {{BaseURL0}}/sample-annotation/all?pageNumber=8&pageSize=7 HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}


### sampleAnnotation GetSearch
GET {{BaseURL0}}/sample-annotation/search?bar=18&pageNumber=2&pageSize=3 HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}


### sampleAnnotation PostOne
POST {{BaseURL0}}/sample-annotation/one HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

{
    "foo": "새로운 한 주",
    "bar": 1234
}


### sampleAnnotation PostList
POST {{BaseURL0}}/sample-annotation/list HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

[
    {
        "foo": "새로운 한 주 시작",
        "bar": 1234
    },
    {
        "foo": "새로운 한 주 즐겁고",
        "bar": 1234
    },
    {
        "foo": "새로운 한 주 보람차게",
        "bar": 1234
    }
]


### sampleAnnotation PutOne
PUT {{BaseURL0}}/sample-annotation/one HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

{
    "id": 152,
    "foo": "PUT으로 새로운 한 주 시작",
    "bar": 12345
}


### sampleAnnotation PutList
PUT {{BaseURL0}}/sample-annotation/list HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

[
    {
        "id": 141
    },
    {
        "id": 152,
        "foo": "PUT리스트 새로운 한 주 시작",
        "bar": 1234
    }
]


### sampleAnnotation DeleteOne
DELETE {{BaseURL0}}/sample-annotation/one HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

{
    "id": -151,
    "status": 777
}


### sampleAnnotation DeleteList
DELETE {{BaseURL0}}/sample-simple/list HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}

[
    {
        "id": -152,
        "status": 777
    },
    {
        "id": 153,
        "status": 7777
    }
]



### Upload Image File - Form Data
POST {{BaseURL0}}/sample-simple/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{tokenAccess}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

6
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

파일 설명입니다.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="graffiti-569265_1920.jpg"
Content-Type: image/jpeg

< d:/WorkSpace/template-spring-boot-3/document/readme.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Download Image File
GET {{BaseURL0}}/sample-simple/file/download/octosys HTTP/1.1
content-Type: application/json
Authorization: Bearer {{tokenAccess}}




### LSITS Sample GetMenu
GET http://localhost:8080/api/common/menu/main HTTP/1.1

